# train_config.yml

device: "cuda"

paths:
  data_dir:  "/mnt/c/Users/narun/OneDrive/Desktop/Project/Heat_MGN/training_dataset"
  output_dir: "/mnt/c/Users/narun/OneDrive/Desktop/Project/Heat_MGN/trained_model"
  # model_dir: "/mnt/c/Users/narun/OneDrive/Desktop/Project/Hydrogel_MGN/Hydrogel_MGN/trained_model/2025-06-05T15h45m54s/model_checkpoint"
  model_dir: null
training:
  num_epochs: 5
  learning_rate: 1e-4
  weight_decay: 5e-3
  trial_passes: 9
  time_window: 10
  message_passing_steps: 15
  add_noise: 0.05
  attention: false
model:
  node_feature_size: 2
  mesh_edge_feature_size: 5
  output_size: 1
  latent_size: 128
  timestep: 1e-5
