device: cuda
paths:
  data_dir: ./dataset/trainset
  model_dir: ./trained_models/
  continue_model_path: ./trained_models/20251019T133039/best_model
model: 
  node_in_dim: 14
  edge_in_dim: 5
  node_out_dim: 1
  hidden_size: 128
  process_steps: 8
  attention: False
  time_window: 10
training:
  learning_rate: 1e-4
  weight_decay: 1e-5
  num_epochs: 100
  start_noise_level: 0.01
  end_noise_level: 0.003
